zlib: upgrade to 1.3.2
* werror-undef.patch partially reverts
https://github.com/madler/zlib/commit/7108497fda9d4536a1afade7f42266e06dca4488
so the build doesn't fail with
In file included from /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/zlib/zlib.h:37,
                 from /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/sal/rtl/crc.cxx:24:
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/zlib/zconf.h:446:5: error: "HAVE_UNISTD_H" is not defined, evaluates to 0 [-Werror=undef]
  446 | #if HAVE_UNISTD_H     /* may be set to #if 1 by ./configure */
      |     ^~~~~~~~~~~~~
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/zlib/zconf.h:450:5: error: "HAVE_STDARG_H" is not defined, evaluates to 0 [-Werror=undef]
  450 | #if HAVE_STDARG_H     /* may be set to #if 1 by ./configure */
      |     ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Change-Id: I8f1dbaf627a573b9a5ff8c9f20061ec482b87c8d
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/199616
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Jenkins