zxing-cpp: Upgrade to 3.0.0
* 0001-const-up-some-symbols.patch has been fixed upstream

* Add gcc12-format.patch to fix 'fatal error: 'format' file not found
  #include <format>'

* Add deprecatedMultiFormatWriter.patch to fix
cui/source/dialogs/QrCodeGenDialog.cxx:158:50: error: ‘ZXing::MultiFormatWriter::MultiFormatWriter(ZXing::BarcodeFormat)’ is deprecated: use CreateBarcode() [-Werror=deprecated-declarations]
  158 |     auto writer = ZXing::MultiFormatWriter(format).setMargin(aQRBorder).setEccLevel(bqrEcc);

TODO: fix the deprecated warning

Downloaded from https://github.com/zxing-cpp/zxing-cpp/releases/download/v3.0.0/zxing-cpp-3.0.0.tar.gz

Change-Id: Icff1a67b4c0441ded4a87212763a998f2889e264
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/199178
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>