fast_float: upgrade to 8.2.3
* 0001-fix-warning-C4702-unreachable-code.patch fixes
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\fast_float\include\fast_float\float_common.h(317) : error C2220: the following warning is treated as an error
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\fast_float\include\fast_float\float_common.h(373) : error C2220: the following warning is treated as an error
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\fast_float\include\fast_float\float_common.h(317) : warning C4702: unreachable code
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\fast_float\include\fast_float\float_common.h(373)
: warning C4702: unreachable code

Downloaded from https://github.com/fastfloat/fast_float/archive/refs/tags/v8.2.3.tar.gz

Change-Id: I39b16bf5770b8295b062c7319a465a25f4c22722
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/198800
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Jenkins