external/harfbuzz: Silence new Clang 24 trunk -Werror,-Wunused-template
> In file included from ../src/hb-number.cc:26:
> In file included from ../src/hb.hh:560:
> ../src/hb-meta.hh:131:3: error: unused function template 'operator()' [-Werror,-Wunused-template]
>   131 |   operator () (T&& v) const HB_AUTO_RETURN (std::forward<T> (v))
>       |   ^~~~~~~~

etc.

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I69284c010e4970db55ecb6e1507186648b8b5271
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/7282
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
(cherry picked from commit 6b03159992ce09f1b63a799ca99476c048758054)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/208278
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>