CppunitTest_sc_pdf_export: fix test on Windows
gerrit_windows_wsl was configure to build with 'make build'
so this failure wasn't caught in time.
Now gerrit_windows_wsl builds with 'make build unitcheck slowcheck'
and it fails with
[_RUN_____] testUnoCommands_Tdf120161::TestBody
warn:vcl:5228:2004:vcl/win/window/salframe.cxx:1046: WinSalFrame::SetIcon(): Could not load large icon !
warn:vcl:5228:2004:vcl/win/window/salframe.cxx:1047: WinSalFrame::SetIcon(): Could not load small icon !
testUnoCommands_Tdf120161::TestBody finished in: 1441ms
E:/jenkins/workspace/gerrit_windows_wsl/sc/qa/extras/scpdfexport.cxx(791) : error : Assertion
Test name: testTdf120190::TestBody
equality assertion failed
- Expected: 1
- Actual  :

Change-Id: I4c3aa541dd4383a39698c23debcd753b0951d59e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/208179
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Xisco Fauli <xiscofauli@libreoffice.org>