CppunitTest_sw_core_text: disable test on Windows
gerrit_windows_wsl was configure to build with 'make build'
so this failure wasn't caught in time.
Now gerrit_windows_wsl builds with 'make build unitcheck slowcheck'
and it fails with
[_RUN_____] testTdf89288_KerningBehaviorBetweenScriptTypes::TestBody
warn:vcl:9072:11396:vcl/win/window/salframe.cxx:1046: WinSalFrame::SetIcon(): Could not load large icon !
warn:vcl:9072:11396:vcl/win/window/salframe.cxx:1047: WinSalFrame::SetIcon(): Could not load small icon !
file:///E:/jenkins/workspace/gerrit_windows_wsl/sw/qa/core/text/data/tdf89288.fodt:
testTdf89288_KerningBehaviorBetweenScriptTypes::TestBody finished in: 663ms
E:/jenkins/workspace/gerrit_windows_wsl/sw/qa/core/text/text.cxx(1716) : error : Assertion
Test name: testTdf161990::TestBody
equality assertion failed
- Expected: P
- Actual  :

Failures !!!
Run: 83   Failure total: 1   Failures: 1   Errors: 0

Change-Id: I6deaddb2c82d8f922f133ec557b868db167a1f14
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/208183
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Xisco Fauli <xiscofauli@libreoffice.org>