pdfium: downgrade to 7681
At least for me, it fails with
[CXX] workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp
test -f /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp || (echo "Missing generated source file /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp" && false)
S=/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice && I=$S/instdir && W=$S/workdir &&  mkdir -p $W/GenCxxObject/UnpackedTarball/pdfium/core/fxcrt/ $W/Dep/GenCxxObject/UnpackedTarball/pdfium/core/fxcrt/ && cd /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice && CCACHE_CPP2=1 CCACHE_DEPEND=1  	  /usr/bin/ccache clang++ -DCPPU_ENV=gcc3 -DLINUX -DOSL_DEBUG_LEVEL=1 -DSAL_LOG_INFO -DSAL_LOG_WARN -DUNIX -DUNX -DX86_64 -D_PTHREADS -D_REENTRANT  -DFPDF_IMPLEMENTATION -DUSE_SYSTEM_LCMS2 -DUSE_SYSTEM_LIBJPEG -DUSE_SYSTEM_ZLIB -DUSE_SYSTEM_ICUUC -DMEMORY_TOOL_REPLACES_ALLOCATOR -DUNICODE -DWIN32_LEAN_AND_MEAN -DCOMPONENT_BUILD  -DZLIB_CONST  -DDEFINE_PS_TABLES_DATA   -fvisibility=hidden         -Wall -Wno-missing-braces -Wendif-labels -Wextra -Wundef -Wunreachable-code -Wshadow -Wunused-macros -finput-charset=UTF-8 -fmessage-length=0 -fno-common -pipe -fstack-protector-strong -Wdeprecated-copy-dtor -Wduplicated-cond -Wlogical-op -Wshift-overflow=2 -Wunused-const-variable=1 -fvisibility-inlines-hidden -fPIC -Wshadow -Woverloaded-virtual -std=c++20 -pthread -O0 -Wp,-U_FORTIFY_SOURCE -fstrict-aliasing -fstrict-overflow -ggdb2 -gsplit-dwarf -gdwarf-4 -ggnu-pubnames -fexceptions -w -DLIBO_INTERNAL_ONLY  -c $W/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp -o $W/GenCxxObject/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.o -MMD -MT $W/GenCxxObject/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.o -MP -MF $W/Dep/GenCxxObject/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.d_ -isystem $W/UnpackedTarball/freetype/include -I$W/UnpackedTarball/icu/source -I$W/UnpackedTarball/icu/source/i18n -I$W/UnpackedTarball/icu/source/common -I$W/UnpackedTarball/zlib -I$W/UnpackedTarball/lcms2/include -I$W/UnpackedTarball/libjpeg-turbo/src -I$W/UnpackedTarball/pdfium -I$W/UnpackedTarball/pdfium/third_party -I$W/UnpackedTarball/pdfium/third_party/agg23 -I$W/UnpackedTarball/pdfium/third_party/abseil-cpp -I$W/UnpackedTarball/pdfium/third_party/fast_float  -I$S/include -I/usr/lib/jvm/java-17-openjdk-amd64/include -I/usr/lib/jvm/java-17-openjdk-amd64/include/linux -I$S/config_host         && mv $W/Dep/GenCxxObject/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.d_ $W/Dep/GenCxxObject/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.d
In file included from /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:5:
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.h:40:53: error: member reference type 'std::vector<unsigned char, FxPartitionAllocAllocator<unsigned char, &pdfium::internal::AllocOrDie, &pdfium::internal::Dealloc>>' is not a pointer; did you mean to use '.'?
      : CFX_ReadOnlySpanStream(pdfium::as_bytes(data->span())),
                                                ~~~~^~
                                                    .
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:10:16: note: in instantiation of member function 'CFX_ReadOnlyContainerStream<std::vector<unsigned char, FxPartitionAllocAllocator<unsigned char, &pdfium::internal::AllocOrDie, &pdfium::internal::Dealloc>>>::CFX_ReadOnlyContainerStream' requested here
template class CFX_ReadOnlyContainerStream<DataVector<uint8_t>>;
               ^
In file included from /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:5:
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.h:40:55: error: no member named 'span' in 'std::vector<unsigned char, FxPartitionAllocAllocator<unsigned char, &pdfium::internal::AllocOrDie, &pdfium::internal::Dealloc>>'
      : CFX_ReadOnlySpanStream(pdfium::as_bytes(data->span())),
                                                ~~~~  ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.h:45:54: error: no member named 'span' in 'std::vector<unsigned char, FxPartitionAllocAllocator<unsigned char, &pdfium::internal::AllocOrDie, &pdfium::internal::Dealloc>>'
      : CFX_ReadOnlySpanStream(pdfium::as_bytes(data.span())),
                                                ~~~~ ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:10:16: note: in instantiation of member function 'CFX_ReadOnlyContainerStream<std::vector<unsigned char, FxPartitionAllocAllocator<unsigned char, &pdfium::internal::AllocOrDie, &pdfium::internal::Dealloc>>>::CFX_ReadOnlyContainerStream' requested here
template class CFX_ReadOnlyContainerStream<DataVector<uint8_t>>;
               ^
In file included from /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:5:
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.h:40:53: error: member reference type 'fxcrt::FixedSizeDataVector<unsigned char>' is not a pointer; did you mean to use '.'?
      : CFX_ReadOnlySpanStream(pdfium::as_bytes(data->span())),
                                                ~~~~^~
                                                    .
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:11:16: note: in instantiation of member function 'CFX_ReadOnlyContainerStream<fxcrt::FixedSizeDataVector<unsigned char>>::CFX_ReadOnlyContainerStream' requested here
template class CFX_ReadOnlyContainerStream<FixedSizeDataVector<uint8_t>>;
               ^
In file included from /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:5:
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.h:50:32: error: no matching function for call to 'as_byte_span'
      : CFX_ReadOnlySpanStream(pdfium::as_byte_span(data)),
                               ^~~~~~~~~~~~~~~~~~~~
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:11:16: note: in instantiation of member function 'CFX_ReadOnlyContainerStream<fxcrt::FixedSizeDataVector<unsigned char>>::CFX_ReadOnlyContainerStream' requested here
template class CFX_ReadOnlyContainerStream<FixedSizeDataVector<uint8_t>>;
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1513:16: note: candidate template ignored: constraints not satisfied [with ExplicitArgumentBarrier = <>, T = fxcrt::FixedSizeDataVector<unsigned char>]
constexpr auto as_byte_span(const T& t LIFETIME_BOUND) {
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1512:22: note: because 'const fxcrt::FixedSizeDataVector<unsigned char> &' does not satisfy 'ByteSpanConstructibleFrom'
  requires(internal::ByteSpanConstructibleFrom<const T&>)
                     ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:418:5: note: because 'const fxcrt::FixedSizeDataVector<unsigned char> &' does not satisfy 'SpanConstructibleFrom'
    SpanConstructibleFrom<T> &&
    ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:361:51: note: because 'span(std::forward<T>(t))' would be invalid: no viable constructor or deduction guide for deduction of template arguments of 'span'
concept SpanConstructibleFrom = requires(T&& t) { span(std::forward<T>(t)); };
                                                  ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1524:16: note: candidate template ignored: constraints not satisfied [with ExplicitArgumentBarrier = <>, T = fxcrt::FixedSizeDataVector<unsigned char>]
constexpr auto as_byte_span(const T& t) {
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1522:22: note: because 'const fxcrt::FixedSizeDataVector<unsigned char> &' does not satisfy 'ByteSpanConstructibleFrom'
  requires(internal::ByteSpanConstructibleFrom<const T&> &&
                     ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:418:5: note: because 'const fxcrt::FixedSizeDataVector<unsigned char> &' does not satisfy 'SpanConstructibleFrom'
    SpanConstructibleFrom<T> &&
    ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:361:51: note: because 'span(std::forward<T>(t))' would be invalid: no viable constructor or deduction guide for deduction of template arguments of 'span'
concept SpanConstructibleFrom = requires(T&& t) { span(std::forward<T>(t)); };
                                                  ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1538:16: note: candidate template ignored: could not match 'ElementType[Extent]' against 'fxcrt::FixedSizeDataVector<unsigned char>'
constexpr auto as_byte_span(const ElementType (&arr LIFETIME_BOUND)[Extent]) {
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1518:16: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr auto as_byte_span(allow_nonunique_obj_t, const T& t LIFETIME_BOUND) {
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1530:16: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr auto as_byte_span(allow_nonunique_obj_t, const T& t) {
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1543:16: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr auto as_byte_span(allow_nonunique_obj_t,
               ^
In file included from /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:5:
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.h:40:53: error: member reference type 'fxcrt::ByteString' is not a pointer; did you mean to use '.'?
      : CFX_ReadOnlySpanStream(pdfium::as_bytes(data->span())),
                                                ~~~~^~
                                                    .
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:12:16: note: in instantiation of member function 'CFX_ReadOnlyContainerStream<fxcrt::ByteString>::CFX_ReadOnlyContainerStream' requested here
template class CFX_ReadOnlyContainerStream<ByteString>;
               ^
In file included from /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:5:
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.h:45:54: error: no member named 'span' in 'std::unique_ptr<fxcrt::MappedDataBytes>'
      : CFX_ReadOnlySpanStream(pdfium::as_bytes(data.span())),
                                                ~~~~ ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:15:16: note: in instantiation of member function 'CFX_ReadOnlyContainerStream<std::unique_ptr<fxcrt::MappedDataBytes>>::CFX_ReadOnlyContainerStream' requested here
template class CFX_ReadOnlyContainerStream<std::unique_ptr<MappedDataBytes>>;
               ^
In file included from /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:5:
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.h:50:32: error: no matching function for call to 'as_byte_span'
      : CFX_ReadOnlySpanStream(pdfium::as_byte_span(data)),
                               ^~~~~~~~~~~~~~~~~~~~
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.cpp:15:16: note: in instantiation of member function 'CFX_ReadOnlyContainerStream<std::unique_ptr<fxcrt::MappedDataBytes>>::CFX_ReadOnlyContainerStream' requested here
template class CFX_ReadOnlyContainerStream<std::unique_ptr<MappedDataBytes>>;
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1513:16: note: candidate template ignored: constraints not satisfied [with ExplicitArgumentBarrier = <>, T = std::unique_ptr<fxcrt::MappedDataBytes>]
constexpr auto as_byte_span(const T& t LIFETIME_BOUND) {
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1512:22: note: because 'const std::unique_ptr<fxcrt::MappedDataBytes> &' does not satisfy 'ByteSpanConstructibleFrom'
  requires(internal::ByteSpanConstructibleFrom<const T&>)
                     ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:418:5: note: because 'const std::unique_ptr<fxcrt::MappedDataBytes> &' does not satisfy 'SpanConstructibleFrom'
    SpanConstructibleFrom<T> &&
    ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:361:51: note: because 'span(std::forward<T>(t))' would be invalid: no viable constructor or deduction guide for deduction of template arguments of 'span'
concept SpanConstructibleFrom = requires(T&& t) { span(std::forward<T>(t)); };
                                                  ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1524:16: note: candidate template ignored: constraints not satisfied [with ExplicitArgumentBarrier = <>, T = std::unique_ptr<fxcrt::MappedDataBytes>]
constexpr auto as_byte_span(const T& t) {
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1522:22: note: because 'const std::unique_ptr<fxcrt::MappedDataBytes> &' does not satisfy 'ByteSpanConstructibleFrom'
  requires(internal::ByteSpanConstructibleFrom<const T&> &&
                     ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:418:5: note: because 'const std::unique_ptr<fxcrt::MappedDataBytes> &' does not satisfy 'SpanConstructibleFrom'
    SpanConstructibleFrom<T> &&
    ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:361:51: note: because 'span(std::forward<T>(t))' would be invalid: no viable constructor or deduction guide for deduction of template arguments of 'span'
concept SpanConstructibleFrom = requires(T&& t) { span(std::forward<T>(t)); };
                                                  ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1538:16: note: candidate template ignored: could not match 'ElementType[Extent]' against 'std::unique_ptr<fxcrt::MappedDataBytes>'
constexpr auto as_byte_span(const ElementType (&arr LIFETIME_BOUND)[Extent]) {
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1518:16: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr auto as_byte_span(allow_nonunique_obj_t, const T& t LIFETIME_BOUND) {
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1530:16: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr auto as_byte_span(allow_nonunique_obj_t, const T& t) {
               ^
/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/UnpackedTarball/pdfium/core/fxcrt/span.h:1543:16: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr auto as_byte_span(allow_nonunique_obj_t,
               ^
8 errors generated.
make: *** [/mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/solenv/gbuild/LinkTarget.mk:402: /mnt/4d311c06-5193-4f61-a3f6-53ca4d9ea1e1/libreoffice/workdir/GenCxxObject/UnpackedTarball/pdfium/core/fxcrt/cfx_read_only_container_stream.o] Error 1

After
commit bb5a91ec17e12a8d9a7d3005ec1de673fc47e0eb
Author: Miklos Vajna <vmiklos@collabora.com>
Date:   Wed Feb 18 10:56:28 2026 +0100

    pdfium: update to 7691

Change-Id: I83a864d8a6263416fed86ab60598a65f715b1651
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/199714
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Jenkins